### ISSUE TITLE
%chart does not support queries written in Standard SQL

### ISSUE THREAD

**Issue by dwmclary** [googledatalab/pydatalab#145]
%chart magic fails when queries use Standard SQL, regardless of whether the module referenced specifies dialect.

To validate:
When "myModule" is defined as:
%%sql 
SELECT a, b FROM [table]

The following works:
%chart bars -d myModule -f a,b 

However, if "myModule" is defined as:
%%sql
SELECT a,b FROM `table`

The same command (%chart bars -d myModule -f a,b) fails.

Either adding a dialect flag for chart or respecting flags from the module would suffice to solve this.

**Comment by yebrahim** [comment]
Obsolete since the new release.
