### ISSUE TITLE
Bug: dialect parameter has no effect when using %%sql --module ..

### ISSUE THREAD

**Issue by parthea** [googledatalab/pydatalab#147]
[An issue was reported on StackOverflow](http://stackoverflow.com/questions/41944649/datalab-how-to-export-big-query-standard-sql-query-to-dataframe) related to the dialect parameter not being honored when using `%%sql --module ...`. This feels like a bug.

The `-d standard` which is used to set the BigQuery dialect to Standard SQL has no effect in the following example:
``
%%sql --module data_name -d standard
``

Currently users still need to specify the dialect parameter when calling `bq.Query.to_dataframe()` which could be confusing.
```
bq.Query(data_name).to_dataframe(dialect='standard')
```

The following works as expected (i.e. when `--module` is not used in `%%sql`)
``
%%sql -d standard
<sql query>
``

**Comment by yebrahim** [comment]
Obsolete since the new release.
