### ISSUE TITLE
%%sql fails if the first line in the SQL query is a comment

### ISSUE THREAD

**Issue by parthea** [googledatalab/pydatalab#148]
I see the following error message if I put a comment above my SQL query when using `%%sql`
`>%sql arguments: name 'comment' is not defined from code '--comment`

Using the following code:
```
%%sql
--comment
SELECT * FROM MyDataSet.MyTable
```

If I move the comment after my SQL query, I won't see the error:

```
%%sql
SELECT * FROM MyDataSet.MyTable
--comment
```

**Comment by yebrahim** [comment]
This was fixed with the new `%bq query` magic.

**Comment by parthea** [comment]
Thanks @yebrahim !
