### ISSUE TITLE
datalab/bigquery/_utils.py parse_table_name should support Standard SQL table naming

### ISSUE THREAD

**Issue by mbookman** [googledatalab/pydatalab#176]
Currently the Table() constructor (via parse_table_name) supports:

      name: the name of the table either as a string or a 3-part tuple (projectid, datasetid, name).
        If a string, it must have the form '<project>:<dataset>.<table>' or '<dataset>.<table>'.

Standard SQL syntax is for `project.dataset.table`.

**Comment by yebrahim** [comment]
Thanks for opening this, I was just looking at it. Maybe we should look into taking the different parts as parameters so we can serialize them correctly according to SQL dialect.

**Comment by mbookman** [comment]
That sounds good. Would than mean doing away with Table._full_name, which would then be constructed based on context?

I'm presently trying to have a block like this:

```
%%bigquery execute --dialect standard
SELECT
  *
FROM
  `$TABLE`
```

and find that if I set TABLE to:

`TABLE = bq.Table('dataset_name.table_name', context.Context('project_id', None))`

Then it gets expanded out as:

```
SELECT
  *
FROM
  `[project_id:dataset_name.table_name]`
```

and I get:

`invalid: Invalid table name: [project_id:dataset_name.table_name]`

which looks to be just what you reported in #172.

**Comment by yebrahim** [comment]
Yes it's related. The name generation should take the dialect into consideration, right now it's not. We should probably switch to a method instead of an attribute `__full_name`.

Btw, if you've already looked through the code and feel like it, feel free to submit a PR. Otherwise I'll take a look at this as soon as I can. :)

**Comment by yebrahim** [comment]
This is obsolete now with the GA changes. Standard SQL is handled properly in the new datalab.google namespace and the `%bq query` magic.
