### ISSUE TITLE
Add magic command %%gsheet to integrate with Google Sheets

### ISSUE THREAD

**Issue by parthea** [googledatalab/pydatalab#261]
From http://stackoverflow.com/questions/42561393/can-i-export-to-google-sheets-from-datalab,

It could be useful to allow users to export a Pandas DataFrame to Google Sheets, potentially through a magic command.

For example,
<code>
%%gsheet -name MyTestSpreadsheet -data DataFrame
</code>

In order for this to work, the GCE VM service account would need to be given access to the specific google sheet prior to running this command.

Taking this one step further, Google sheets could also potentially be added as a BigQuery QueryOutput type.
https://github.com/googledatalab/pydatalab/blob/52939eec085dcd211e133cbc3e0676a0b266c41d/google/datalab/bigquery/_query_output.py

**Comment by nikhilk** [comment]
We should definitely think through Google Sheets integration with BigQuery and DataFrames.

The top-level question I have is whether we can do this immediately without per-user auth tokens (we hope to support those in not too distant future, but not immediately).

**Comment by parthea** [comment]
Closing as obsolete.
