### ISSUE TITLE
Unable to use %gcs to copy files - unexpected auth error

### ISSUE THREAD

**Issue by nikhilk** [googledatalab/pydatalab#271]
%gcs copy -s gs://cloud-ml-data/census/ss14psd.csv -d /content/workspace/census/data/census.csv

Result:
````
Couldn't copy gs://cloud-ml-data/census/ss14psd.csv to /content/workspace/census/data/census.csv: HTTP request failed: Caller does not have storage.objects.create access to bucket cloud-ml-data.
````

However, this works:

    !gsutil -q cp gs://cloud-ml-data/census/ss14psd.csv /content/workspace/census/data/census.csv

Expected %gcs to work just as well...

**Comment by yebrahim** [comment]
This is due to `%gcs` not supporting copying to local paths. We should look at adding that feature.

**Comment by yebrahim** [comment]
Closed in favor of https://github.com/googledatalab/pydatalab/issues/303.
