### ISSUE TITLE
census notebook 2 broken at head with BQ error in analyze

### ISSUE THREAD

**Issue by brandondutra** [googledatalab/pydatalab#305]
steps to reproduce:
1) build datalab from datalab/containers/datalab/build.sh pydatalab-location
2) datalab and pydatalab repros are at master
3) go to the census regression sample. Run notebook 1. Then run notebook 2. the call to analyze fails.

I extracted the code that fails, and there is some kind of problem with BQ. Note that this error does NOT show up if you run the sample from the released version (datalab create <name>)

```
import google.datalab.bigquery as bq
import json
sql = 'SELECT  max(WAGP) as max_WAGP, min(WAGP) as min_WAGP, avg(WAGP) as avg_WAGP  from csv_table'
with open('/content/datalab/workspace/census/data/schema.json', 'r') as f:
  schema_list = json.loads(f.read())
print('data path', train_data_path)
print('schema', schema_list)
table = bq.ExternalDataSource(
        source=train_data_path,
        schema=bq.Schema(schema_list))
query = bq.Query(sql, data_sources={'csv_table': table})
#numerical_results = query.execute().result().to_dataframe()
print('query', query)
query.execute()
```

The execute errors with:

```
TypeErrorTraceback (most recent call last)
<ipython-input-30-1db4c8609bfb> in <module>()
     12 #numerical_results = query.execute().result().to_dataframe()
     13 print('query', query)
---> 14 query.execute()

/usr/local/lib/python2.7/dist-packages/google/datalab/bigquery/_query.pyc in execute(self, output_options, sampling, context, query_params)
    334     """
    335     return self.execute_async(output_options, sampling=sampling, context=context,
--> 336                               query_params=query_params).wait()

/usr/local/lib/python2.7/dist-packages/google/datalab/bigquery/_query.pyc in execute_async(self, output_options, sampling, context, query_params)
    267                                            query_params=query_params)
    268     except Exception as e:
--> 269       raise e
    270     if 'jobReference' not in query_result:
    271       raise Exception('Unexpected response from server')

TypeError: list indices must be integers, not tuple
```

@qimingj or @yebrahim, have you seen this BQ error before?

**Comment by yebrahim** [comment]
Looks to me like a schema error. Can you paste the schema file?

**Comment by qimingj** [comment]
I am not able to reproduce the problem. Maybe it is BQ flakiness?

**Comment by brandondutra** [comment]
query: BigQuery Query - SELECT  max(WAGP) as max_WAGP, min(WAGP) as min_WAGP, avg(WAGP) as avg_WAGP  from csv_table

schema
```
[
  {
    "type": "FLOAT", 
    "name": "WAGP"
  }, 
  {
    "type": "STRING", 
    "name": "SERIALNO"
  }, 
  {
    "type": "STRING", 
    "name": "AGEP"
  }, 
  {
    "type": "STRING", 
    "name": "COW"
  }, 
  {
    "type": "STRING", 
    "name": "ESP"
  }, 
  {
    "type": "STRING", 
    "name": "ESR"
  }, 
  {
    "type": "STRING", 
    "name": "FOD1P"
  }, 
  {
    "type": "STRING", 
    "name": "HINS4"
  }, 
  {
    "type": "STRING", 
    "name": "INDP"
  }, 
  {
    "type": "STRING", 
    "name": "JWMNP"
  }, 
  {
    "type": "STRING", 
    "name": "JWTR"
  }, 
  {
    "type": "STRING", 
    "name": "MAR"
  }, 
  {
    "type": "STRING", 
    "name": "POWPUMA"
  }, 
  {
    "type": "STRING", 
    "name": "PUMA"
  }, 
  {
    "type": "STRING", 
    "name": "RAC1P"
  }, 
  {
    "type": "STRING", 
    "name": "SCHL"
  }, 
  {
    "type": "STRING", 
    "name": "SCIENGRLP"
  }, 
  {
    "type": "STRING", 
    "name": "SEX"
  }, 
  {
    "type": "STRING", 
    "name": "WKW"
  }
]
```
train data: gs://cloud-ml-dev-datalab-workspace/census/data/train.csv'

I'll try rebuilding the container again today. I guess the more interesting thing to do is to add more unit and e2e tests on the mltoolbox packages.

**Comment by brandondutra** [comment]
strange. I rebuild the container with the latest masters from pydatalab/datalab and I still get this error.

**Comment by brandondutra** [comment]
printed the trace in _query:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/google/datalab/bigquery/_query.py", line 269, in execute_async
    query_params=query_params)
  File "/usr/local/lib/python2.7/dist-packages/google/datalab/bigquery/_api.py", line 182, in jobs_insert_query
    expanded_definitions[td] = table_definitions[td]._to_query_json()
TypeError: list indices must be integers, not tuple
```

Next, I printed the td value in _api:
        print('table_definitions', table_definitions)
        print('td', td)
(u'table_definitions', [('csv_table', BigQuery External Datasource - paths: /content/datalab/workspace/census/data/train.csv)])
(u'td', ('csv_table', BigQuery External Datasource - paths: /content/datalab/workspace/census/data/train.csv))

So table_definitions is a list of (str, bq.ExternalDataSource), not a dict! The docs of jobs_insert_query say table_definitions should be a dict. So the bug is in _query.py:Query:__init__() which has self._data_sources as a list, but it should be a dict.

**Comment by brandondutra** [comment]
so the problem is that in _query.py
1. data_sources() should return a dict, not list of tuple
1. dry_run(): table_definitions should be passed a dict, not list (maybe from self.data_sources)
1. execute_async(): same as in dry_run()
