### ISSUE TITLE
Array as a query parameter

### ISSUE THREAD

**Issue by JokullJohanns** [googledatalab/pydatalab#317]
Hi,

I'm trying to filter a query by using a python array. Am I doing something wrong or is this not supported yet?

The following query is a test query I'm trying to run to test this...

```test_query = bq.Query(sql="SELECT 3 IN (@arr) AS res")

query_parameters = [
  {
    'name': 'arr',
    'parameterType': {'type': 'ARRAY<INTEGER>'},
    'parameterValue': {'value': '[2,3,4]'}
  }
]
job = test_query.execute(query_params=query_parameters)
job.result()

**Comment by yebrahim** [comment]
It's supported, but you have to use the BigQuery syntax, since we're passing your parameters as-is to the BigQuery service. You can see an example [here](https://cloud.google.com/bigquery/querying-data#using_arrays_in_parameterized_queries) (switch to API example). Here's a more focused `query_parameters` object:
```
query_parameters = [
  {
    'name': 'myparam',
    'parameterType': {
      'type': 'ARRAY',
      'arrayType': {
        'type': 'INT64'
      }
    },
    'parameterValue': {
      'arrayValues': [
        {
          'value': '2'
        },
        {
          'value': '3'
        },
        {
          'value': '4'
        },
      ]
    }
  }
]
```

Our `bq execute` magic command does not support this yet though, we'll look into making the experience easier using that magic.

**Comment by JokullJohanns** [comment]
Thank you @yebrahim for a quick reply!

Great, this works!

Do you know how this scales?

I haven't tested this thoroughly but I plan on using this in this manner....

```
test_query = bq.Query(sql="select * from *some_table_name*  where id in unnest(@idArr)")
arr = large_dataframe.id.values #A python list of integers

query_parameters = [
  {
    'name': 'idArr',
    'parameterType': {
      'type': 'ARRAY',
      'arrayType': {
        'type': 'INT64'
      }
    },
    'parameterValue': {
      'arrayValues': [{'value':str(x)} for x in arr] 
    }
  }
]
job = test_query.execute(query_params=query_parameters)
job.result()
```

**Comment by yebrahim** [comment]
Yes, that should do it. Btw, you don't need the quotes around the `INT64` types, the values could also be:
```
'value': 2
```
As long as it's "INT64-parsable", you're fine.
