### ISSUE TITLE
Python 3 TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by shengnwen** [googledatalab/pydatalab#318]
I'm testing the pydatalab GA 1.0 version. It seems has python3 incompatible problems.
When I am running '%bq tables ls', it throws: Type Error: 'str' does not support the buffer interface.

**Comment by yebrahim** [comment]
I assume you mean `%bq tables list`?
This was actually just recently fixed by https://github.com/googledatalab/pydatalab/pull/316, so if you need that fix you can pull it from master directly, or you can wait for the next pip release.

**Comment by shengnwen** [comment]
Thanks a lot! When can I expect the next pip version been released?

**Comment by yebrahim** [comment]
We're working on creating the next pip package and uploading it soon. Please check the wiki in this repo for updates later this week.
