### ISSUE TITLE
Create documents for pydatalab.

### ISSUE THREAD

**Issue by qimingj** [googledatalab/pydatalab#32]
Basically we'll need something like https://github.com/googledatalab/datalab/tree/datalab-managed/docs.

**Comment by wafisher** [comment]
It would be great if these were online i.e. each user didn't have to build the docs themselves.

**Comment by parthea** [comment]
@wafisher The following link appears to have up-to date content and may be helpful.
http://googledatalab.github.io/pydatalab/

**Comment by wafisher** [comment]
You're right. Not sure how I was expected to find that but I'll bookmark it. Thank you.

**Comment by parthea** [comment]
@wafisher I'm sorry to hear that you had trouble finding the API docs. I ran into a similar issue and I'm not sure that the link is published anywhere (at least I couldn't find it). 

@ojarjur There is an outdated link at https://cloud.google.com/datalab/docs/how-to/manage-notebooks under the heading **Source code and library reference**  that points to an older page http://googledatalab.github.io/datalab/ . On a separate note, I think the heading **Source code and library reference** may fit better under the [Documentation](https://cloud.google.com/datalab/docs/) page.

**Comment by ojarjur** [comment]
@parthea Thanks for pointing out that old link; I'll see about getting it updated.

@wafisher I'm sorry that we haven't gotten this better visibility yet; I've been thinking about the best way to surface these docs and will probably put a link to it somewhere from within the Datalab UI. However, that isn't settled yet.
