### ISSUE TITLE
Update the google.datalab migration guide to include sample code to change the BigQuery billing tier

### ISSUE THREAD

**Issue by parthea** [googledatalab/pydatalab#346]
I wasn't able to find information on how to change the BigQuery billing tier. I looked through the source and found a way , but I'm not sure if it is the correct approach. Could we include sample code on how to change the BigQuery maximum billing tier  in the [google.datalab migration guide](https://github.com/googledatalab/pydatalab/wiki/%60datalab%60-to-%60google.datalab%60-Migration-Guide) ?

Here is code I used:
```
from google.datalab import Context
Context.set_config(Context.default(), {'bigquery_billing_tier': 2})
```

**Comment by yebrahim** [comment]
This is the correct way to set it. You can either create a new, temporary `Context` object and set its config, or you can set it globally on the `Context.default()` directly. I'll see if I can add more info in the migration guide.

**Comment by parthea** [comment]
Thanks @yebrahim !
