### ISSUE TITLE
Broken link on pyDatalab main wiki page: Release Announcements link

### ISSUE THREAD

**Issue by parthea** [googledatalab/pydatalab#352]
On the [pyDatalab Wiki page](https://github.com/googledatalab/pydatalab/wiki), the link titled [Release Announcements](https://github.com/googledatalab/pydatalab/wiki/Release-Info) appears to be broken. The link could be changed to https://github.com/googledatalab/pydatalab/releases instead of https://github.com/googledatalab/pydatalab/wiki/Release-Info.

**Comment by chmeyers** [comment]
Done.

**Comment by parthea** [comment]
Thanks @chmeyers !  I just noticed that the [Python API documentation](http://googlecloudplatform.github.io/datalab/) link under the Resources heading is also broken. The link should be changed to http://googledatalab.github.io/pydatalab/

**Comment by chmeyers** [comment]
Also done.
