### ISSUE TITLE
The SQL Modules and Variable Expansion wiki page references the old datalab magic %%sql

### ISSUE THREAD

**Issue by parthea** [googledatalab/pydatalab#353]
The [SQL Modules and Variable Expansion](https://github.com/googledatalab/pydatalab/wiki/SQL-Modules-and-Variable-Expansion) wiki page references the old `datalab` magic command `%%sql` instead of the new `google.datalab` magic command `%bq`.

**Comment by parthea** [comment]
The old `datalab` magic also appears in [Charting and Chart Controls](https://github.com/googledatalab/pydatalab/wiki/Charting-and-Chart-Controls) and [UDFs](https://github.com/googledatalab/pydatalab/wiki/UDFs) using [Github search](https://github.com/googledatalab/pydatalab/search?utf8=%E2%9C%93&q=sql&type=Wikis).

**Comment by chmeyers** [comment]
SQL Modules don't exist anymore, so these aren't straightforward find/replaces.  It might be okay to remove most of the SQL Modules page at least.  Yasser, do you want to take a look?

**Comment by yebrahim** [comment]
These are still valuable to keep for references of the old package, I'll add a note that mentions this..

**Comment by yebrahim** [comment]
We can close this one now since we have the deprecation message on that page.
