### ISSUE TITLE
Make all storage operations support eventual consistency

### ISSUE THREAD

**Issue by craigcitro** [googledatalab/pydatalab#355]
(This is a follow-on to #344.)

Assuming we don't find any unpleasantness from the new code in #354, we should make all the `google.datalab.storage` operations handle eventual consistency under the hood. The complete info on what's eventually consistent is in the [storage docs](https://cloud.google.com/storage/docs/consistency#eventually_consistent_operations).

**Comment by qimingj** [comment]
Was [storage docs](https://cloud.google.com/storage/docs/consistency#eventually_consistent_operations) updated recently? Now it says all of the following are strongly consistent operations:

Read-after-write
Read-after-metadata-update
Read-after-delete
Bucket listing
Object listing
Granting access to resources

So I guess nothing needs to be done here?

**Comment by craigcitro** [comment]
That's totally plausible: they were working on moving everything to being strongly consistent back around the time I filed this issue, so it's probably moot by now.
