### ISSUE TITLE
Update the homepage link on PyPi

### ISSUE THREAD

**Issue by parthea** [googledatalab/pydatalab#422]
The homepage link on https://pypi.python.org/pypi/datalab/1.0.1 is currently pointing to https://github.com/googledatalab/datalab but I think it should be https://github.com/googledatalab/pydatalab

**Comment by parthea** [comment]
I think the download url should be changed from https://github.com/googledatalab/datalab/tarball/0.1 to https://github.com/googledatalab/pydatalab/tarball/0.1

**Comment by chmeyers** [comment]
Yasser, can you do this since you have the permissions?
