### ISSUE TITLE
where does %bq execute --to-dataframe export to?

### ISSUE THREAD

**Issue by jpvelez** [googledatalab/pydatalab#486]
Hi there,

Trying to figure out how to load query results into a DataFrame using the `%bq` command.

The option you document here seems to be to create a query object, then execute it using dataframe output options from the bq API:

`df = requests.execute(output_options=bq.QueryOutput.dataframe()).result()`

However, the `--to-dataframe` option on `%bq execute` suggest that you should be able to do this directly from the execute command. However, I can't seem to figure out how to save the resulting DataFrame to a variable, and you can't pass a variable name to `--to-dataframe`.

**Comment by qimingj** [comment]
Try:

my_dataframe = %%bq execute -q n1 --to-dataframe

**Comment by jpvelez** [comment]
Oh, fabulous! 

I had no idea you could save the output of magics to variables. Thanks so much!

**Comment by AhmedTareka** [comment]
Hi,

I have been trying this method, however, it does not work when you have defined parameters,
do you know a way to get around it ?

Thank you
