### ISSUE TITLE
Support start_date and end_date to be python expressions

### ISSUE THREAD

**Issue by rajivpb** [googledatalab/pydatalab#522]
Following Bradley's feedback on this (in https://docs.google.com/a/google.com/document/d/15LcgGlktYzrVZ3whFEmOp2bSXXFUE3bfIp_FvkjixP0/edit?disco=AAAABP6Hxlk):

"It should support variable of type datetime too. For example:

previous cell:
start = datetime.now() + timedelta(hours=6)

Then you can do:
start_date: $start"

**Comment by rajivpb** [comment]
CC: @qimingj

**Comment by rajivpb** [comment]
@qimingj : Is it standard practice to have python expressions embedded within a yaml cell body? I'm guessing that this is not true for Datalab, hence the question.

**Comment by qimingj** [comment]
It is confusing to mix python and yaml cell. But I didn't mean to mix the languages. It is common for notebook users to define a python variable somewhere else and in yaml we only need to reference it with {var} or $var.

**Comment by rajivpb** [comment]
Understood (and realize that you had actually specified this in the doc). So this would actually be available for free thanks to parse_config() which actually make it possible to reference datetime objects in the yaml just like any other regular python object. So for example:

Cell 1:
import datetime
now = datetime.datetime.now()
start_time = now + datetime.timedelta(5)

Cell 2:
%%bq pipeline --name regular_extract
extract:
  table: cloud-ml-dev.rajivpb_demo.foo_created
  path: gs://rajivpb-airflow-testing/foo_created_data_%(_ts_nodash)s.csv
schedule:
  start: $start_time

This actually works and produces a valid airflow python spec.

**Comment by qimingj** [comment]
Great!

**Comment by rajivpb** [comment]
Closing since this is the current behaviour.
