### ISSUE TITLE
Fix "User-Authentication" wiki page broken link and missing information

### ISSUE THREAD

**Issue by charlesreid1** [googledatalab/pydatalab#553]
In the wiki for this repository, on the ["Authentication for Google Services"](https://github.com/googledatalab/pydatalab/wiki/Authentication-for-Google-Services) page, there is a link to a User-Authentication page at the following link:

https://github.com/GoogleCloudPlatform/datalab/wiki/User-Authentication

However, this redirects to the wiki in the [googledatalab/datalab](https://github.com/googledatalab/datalab/) repository, because ownership of the datalab repository was changed to the googledatalab organization. Apparently some wiki pages disappeared during that transition. I'm unable to find solid information for how to authenticate using pydatalab, and the procedure detailed on [this page](https://cloud.google.com/docs/authentication/getting-started) (pointing to a JSON file using an environmental variable) does not seem to be working. I've opened an issue in the datalab repository asking that the "User-Authentication" wiki page be added (see [datalab issue #1743](https://github.com/googledatalab/datalab/issues/1743)), but I'd also like to ask that this page be updated with some useful information for user authentication when using pydatalab, or a working link to reliable information.

Thanks!

**Comment by qimingj** [comment]
Thanks for catching this. I updated the page with more relevant info. Please re-open this issue if you have more observations on auth.

https://github.com/googledatalab/pydatalab/wiki/Authentication-for-Google-Services
