### ISSUE TITLE
Table viewer regression

### ISSUE THREAD

**Issue by yebrahim** [googledatalab/pydatalab#558]
Table viewer doesn't display the table data, instead it just returns the table object. You can reproduce this using a %%bq query cell. 
This looks recent, as my two weeks old instance works fine.

**Comment by abhinavrpatel** [comment]
I would love to look into this if it is okay

**Comment by yebrahim** [comment]
We actually fixed this issue last week, turns out it's an HTML registration bug: https://github.com/googledatalab/pydatalab/pull/560.
Sorry I forgot to close it.
