### ISSUE TITLE
Why 2 datalab version? one in root, the another in google folder.

### ISSUE THREAD

**Issue by ZedYeung** [googledatalab/pydatalab#582]
The two version of datalab are quite different.

More specifically, the execute function in pydatalab/datalab/bigquery/_query.py line 496  is 
def execute(self, table_name=None, table_mode='create', use_cache=True, priority='interactive',
while the execute function in pydatalab/google/datalab/bigquery/_query.py line 322 is
def execute(self, output_options=None, sampling=None, context=None, query_params=None):

so, I can output query result to bigquery table with the pydatalab/datalab/bigquery/ with
import datalab.bigquery as bq
bq.Query(query).execute(table_name=name)

while with pydatalab/google/datalab/bigquery/_query.py
import google.datalab.bigquery as bq
bq.Query(query).execute(output_options=bq.QueryOutput.table(name=name))

It is confusing to have two versions, and no explanation about that on Readme.
Thanks!

**Comment by qimingj** [comment]
Added ReadMe https://github.com/googledatalab/pydatalab/tree/master/datalab.

Everything under datalab namespace is actively maintained but no new features are being added. Please use corresponding libraries under google.datalab namespace (source code under google/datalab directory).
