### ISSUE TITLE
why not add mltoolbox to pypi package?

### ISSUE THREAD

**Issue by ZedYeung** [googledatalab/pydatalab#584]
I just noticed that mltoolbox have not been installed by pip install datalab since the solutionbox is not in pypi datalab package.

So I have to clone the whole package and manually install it.

I wonder why not just integrated mltoolbox to datalab pypi package and just put it in a new pypi package.

Or at least add some explanation like the mltoolbox not in pypi, you have to install it manully in Readme.

**Comment by qimingj** [comment]
ML toolbox will enter maintenance mode. New features are being added to ml toolbox (solutionbox/ml_toolbox). Therefore there is no plan to add it to pypi
