### ISSUE TITLE
ModuleNotFoundError: No module named 'mltoolbox'

### ISSUE THREAD

**Issue by ZedYeung** [googledatalab/pydatalab#586]
Acutually, I install the mltoolbox by using python setup.py install(the setup.py in solutionbox/structured_data

When I run this
https://github.com/googledatalab/notebooks/blob/736398fccc3dc9541406175d0e29705ba805db81/samples/ML%20Toolbox/Regression/Census/1%20Local%20End%20to%20End.ipynb
on my local machine.

At first block,
import mltoolbox.regression.dnn as regression
works well.

But at In [17] block, the regression.train just output
```
Training: completed
```

And then I found that the jupyter notebook said:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mltoolbox'
```

That is weird. And then I try to run this notebook on cloudshell datalab. All work well!

That is really painful. What is the right way to install mltoolbox so that I can use it on local machine?

Btw, when the apache beam can support python 3? The progress seems not good.

**Comment by qimingj** [comment]
Can you consistently reproduce the issue? Would it be possible that kernel was reset between first and 17th block run?

I don't know the progress on beam py3 progress. Maybe you can ask in the github repo?

**Comment by ZedYeung** [comment]
yeah, consistently, in virtualenv ptyhon2 and python3 without virtyalenv.
Both of the mltoolbox are munually installed by setup.py or install*.sh.
but it works well on cloud datalab, so i think that is something wrong with
install or dependency.

2017年11月2日 16:44，"qimingj" <notifications@github.com>写道：

**Comment by qimingj** [comment]
How do you install setup.py and which setup.py?

Here is what I did:

1. git clone the pydatalab repo.
2. cd [repo]/solutionbox/structured_data
3. pip install .

To test this, I ran "python" (not in jupyter notebook first), and then "import mltoolbox" and see if it complains.

If not, try it in Jupyter notebook and see if it complains?

**Comment by ZedYeung** [comment]
yeah, actually I

   1. cd [repo]/solutionbox/structured_data

   2. python setup.py install
I think that just same with pip install .?
And after install, I run python in terminal and run import mltoolbox, it
works well.

And in jupyter notebook if i run import mltoolbox it works well, too.

The problem popup only when I run the regression.train in 17th block.

Any way, this issue can be closed since I already doing my job on cloud
datalab.
Besides, I cannot use apache-beam with python3 on my local machine.
So I just decided put my job on cloud datalab.
What is more, tackling such problem is tricky, since there are so many
package dependencies.

I just want to advised that why not just release the mltoolbox to pypi,
just like what i said in issue #584.

2017-11-03 15:31 GMT-07:00 qimingj <notifications@github.com>:
