### ISSUE TITLE
Resources exceeded during query execution: The query could not be executed in the allotted memory.

### ISSUE THREAD

**Issue by ZedYeung** [googledatalab/pydatalab#601]
import mltoolbox.regression.dnn as regression

When this run:
regression.analyze(dataset=train_data, output_dir=analysis_path)
it works well on local machine.

while when run on cloud
regression.analyze(dataset=train_data, output_dir=analysis_path,
cloud=True)

Track BigQuery status at
https://bigquery.cloud.google.com/queries/*********
Running numerical analysis...done.
Running categorical analysis...Analyze: failed with error: HTTP request failed: Resources exceeded during query execution: The query could not be executed in the allotted memory. ORDER BY operator used too much memory. <class 'google.datalab.utils._http.RequestException'> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/google/datalab/_job.py", line 165, in _refresh_state
    self._result = self._future.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mltoolbox/_structured_data/_package.py", line 167, in <lambda>
    fn = lambda: _analyze(output_dir, dataset, cloud, project_id)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/mltoolbox/_structured_data/_package.py", line 206, in _analyze
    preprocess.cloud_preprocess.main(args)
  File "/usr/local/lib/python2.7/dist-packages/mltoolbox/_structured_data/preprocess/cloud_preprocess.py", line 261, in main
    run_analysis(args)
  File "/usr/local/lib/python2.7/dist-packages/mltoolbox/_structured_data/preprocess/cloud_preprocess.py", line 251, in run_analysis
    run_categorical_analysis(table, schema_list, args)
  File "/usr/local/lib/python2.7/dist-packages/mltoolbox/_structured_data/preprocess/cloud_preprocess.py", line 212, in run_categorical_analysis
    df = query.execute().result().to_dataframe()
  File "/usr/local/lib/python2.7/dist-packages/google/datalab/bigquery/_query.py", line 337, in execute
    query_params=query_params).wait()
  File "/usr/local/lib/python2.7/dist-packages/google/datalab/bigquery/_query_job.py", line 84, in wait
    raise e
RequestException: HTTP request failed: Resources exceeded during query execution: The query could not be executed in the allotted memory. ORDER BY operator used too much memory.

I wonder what is this memory means. Obviouly, it is nothing about my local machine, so that means the memory allocated to my project or the memory on google cloud machine or something?

**Comment by qimingj** [comment]
How large is your training data? I think you might have hit Bigquery memory limit.

**Comment by ZedYeung** [comment]
I roughly estimated it.

In one dataset with 16 columns, the bigquery can order about 4.7 million rows(427MB)

In another dataset with 6 columns, the bigquery can order about 12 million rows(467MB)

Yeah, it shows that bigquery is very weak on order by. (500MB cannot be deemed as a large dataset)

I wonder can I increase the memory limit? Is that a quota or the system limit?

**Comment by qimingj** [comment]
Unfortunately, seems no way to increase the memory limit. ORDER BY is an operation that requires a single node to see all data, so it may hit the memory limit of a single node. I don't know any way to customize the node BigQuery uses.

I assume you have string columns. Are these categorical columns (with a few unique values, such as weekday), or are these text columns (many unique values, but can be broken into words or tokens which are limited in unique values)? One suspicion is that you have a text column and it tries to compute all categories, and the total number is too large to sort. In this case, I would recommend using ML Workbench (next version of ML Toolbox, still in contrib), which support text columns (you can do bag of words).

**Comment by ZedYeung** [comment]
You are right. The souce code pydatalab/solutionbox/structured_data/mltoolbox/_structured_data/preprocess/cloud_preprocess.py
line 191-201
```
sql = """
            SELECT
              {name}
            FROM
              {table}
            WHERE
              {name} IS NOT NULL
            GROUP BY
              {name}
            ORDER BY
              {name}
```
shows that bigquery only choose one column and then group by and then order by every time, so it cost not too much.

The problem is the 'id' column since every row have unique id.
But it seems weird to make 'id' column to be numerical.

I think in analysis step, the program should just skip analysis 'key' feature-- I mean the 'id' column, right?

**Comment by qimingj** [comment]
You are right. We should skip key columns for analysis.

In the meantime, perhaps you want to try out ML Workbench (sample notebooks: https://github.com/googledatalab/notebooks/tree/master/samples/contrib/mlworkbench). It is the next version of ML Toolbox --- Command line interface, more data types (image, text), and more model types. In ML Workbench, we only collect vocabulary if a column is categorical or text. If you set transform to "key", then nothing is collected in analysis.

**Comment by ZedYeung** [comment]
Thank you very much. It looks good. That is exactly what i want. 
Before that, I would like to suggest adding bigquery table args in analyze just like 
pydatalab/solutionbox/structured_data/mltoolbox/_structured_data/preprocess/cloud_preprocess.py line 64
```
parser.add_argument('--bigquery-table',
```
But now the mlworkbench already realized that.

Btw, I wonder how can I custom the loss function. 

I would just close this and lauch a new issue about loss function.

Thank you very much.

**Comment by IslamAzab** [comment]
I know this is a bit old, but I am curious would `OVER (PARTITION BY ...` cause to hit the same limit caused by `ORDER BY ...` ?
