### ISSUE TITLE
Replace google.cloud.storage with google.datalab.storage

### ISSUE THREAD

**Issue by rileyjbauer** [googledatalab/pydatalab#660]
We're importing google.cloud.storage here: 
https://github.com/googledatalab/pydatalab/blob/7688b2935673544b52e9b234fce5b78cd1eb8e39/google/datalab/contrib/pipeline/airflow/_airflow.py#L13

but we shouldn't need to add this dependency since we already have google.datalab.storage.

**Comment by rajivpb** [comment]
https://github.com/googledatalab/pydatalab/pull/668

**Comment by rajivpb** [comment]
Thanks for creating this issue for tracking, @rileyjbauer
