### ISSUE TITLE
Please pin dependency version ranges, not specific dependency versions

### ISSUE THREAD

**Issue by jpvelez** [googledatalab/pydatalab#678]
Hi there! Hundreds of data scientists at Spotify use this package every day. It's really awesome. We make it available internally through a Docker image. 

The problem, similar to https://github.com/googledatalab/pydatalab/issues/386, is that this package's practice of pinning specific dependency versions - rather than version ranges, like every other open source python library from Google - makes it a huge, chronic pain to maintain installations of this library. Here is why:

In addition to pydatalab, we install a few dozen standard pydata packages to our internal docker image for data scientists - pandas, numpy, pandas-gbq, etc. Nearly every time we want to release the image, the pydatalab package's hard dependencies cause an insolvable dependency conflict with some other package. As a result, we have to maintain our own patched version of pydatalab in our internal github and release it to our internal pypi, which is a time consuming pain.

Many people at Spotify and surely elsewhere have run into this issue in the past.

The [official python packaging docs](https://packaging.python.org/discussions/install-requires-vs-requirements/) discourage pinning versions in `install_requires` (unlike `requirements.txt`), and no other Google python package seems to do this:

```
datalab==1.1.2            requires configparser==3.5.0, future==0.16.0, futures==3.0.5, google-api-python-client==1.6.2, google-cloud==0.30.0, google_auth_httplib2==0.0.2, httplib2==0.10.3, ipykernel==4.5.2, jsonschema==2.6.0, mock==2.0.0, oauth2client==2.2.0, pandas-profiling>=1.0.0a2, pandas==0.22.0, plotly==1.12.5, psutil==4.3.0, python-dateutil==2.5.0, pytz>=2015.4, pyyaml==3.11, requests==2.9.1, scikit-image==0.13.0, scikit-learn==0.18.2, seaborn==0.7.0, six==1.10.0, urllib3==1.22
 
  google-api-core==1.1.0    requires google-auth<2.0.0dev,>=0.4.0, googleapis-common-protos<2.0dev,>=1.5.3, protobuf>=3.0.0, pytz, requests<3.0.0dev,>=2.18.0, setuptools>=34.0.0, six>=1.10.0
  
  tensorflow==1.7.0         requires absl-py>=0.1.6, astor>=0.6.0, gast>=0.2.0, grpcio>=1.8.6, numpy>=1.13.3, protobuf>=3.4.0, six>=1.10.0, tensorboard<1.8.0,>=1.7.0, termcolor>=1.1.0, wheel>=0.26
```

In fact, because of the pinning practice, pydatalab 1.1.2's _own_ dependencies appear to be conflicted:

datalab -> requests==2.9.1
datalab -> google-cloud==0.30 -> google-api-core<0.2.0dev,>=0.1.1 -> currently resolves to google-api-core==1.1.0 -> requests<3.0,>=2.18.0

One of our internal image release is blocked until we either patch and release pydatalab internally again, or this issue is resolved upstream if you start declaring dependency ranges instead of hard versions (our overwhelming preference, as this reduces the maintenance burden for both of us).

**Comment by jpvelez** [comment]
We've run into this same issue before: https://github.com/googledatalab/pydatalab/pull/483

**Comment by ojarjur** [comment]
I agree with this proposal.

I don't know why we started with exact version requirements (that seems to be the case from the beginning of the repository), but that does not seem appropriate for the library.

We *do* use exact version requirements when building our Docker images in the `datalab` repository, but that is a different context and so exact matches make sense there.

**Comment by jpvelez** [comment]
Fabulous, thank you so much! Do you know when you might be able to release these changes?

**Comment by ojarjur** [comment]
@jpvelez Sorry for the delay in responding.

I'm currently working on/testing the next Datalab release, so I'm not going to start a new PyPI release of the pydatalab library until after that is done.

**Comment by ojarjur** [comment]
The new release has been published on PyPI
