### ISSUE TITLE
Remove use of a deprecated python package, google-cloud

### ISSUE THREAD

**Issue by crwilcox** [googledatalab/pydatalab#698]
This repository contains a setup.py file that depends on 
the `google-cloud` package. This package is deprecated. If you wish to continue
to use this package, please pin the version to `google-cloud<0.34.0`. If you have
more time to dedicate to this, I would advise sorting out which sub-packages you
actually rely on and depending on them.

For further information please view this package on PyPI, https://pypi.org/project/google-cloud/

https://github.com/googledatalab/pydatalab/blob/master/setup.py#L96

**Comment by alienczf** [comment]
fixed in https://github.com/googledatalab/pydatalab/pull/705

please close the ticket?

**Comment by yebrahim** [comment]
Yup, thanks @alienczf.
