### ISSUE TITLE
ImportError: cannot import name 'Aligner'

### ISSUE THREAD

**Issue by elgalu** [googledatalab/pydatalab#704]
https://github.com/googledatalab/pydatalab/blob/a886276bf6fea8defec90d600da1b451ea9d9f2e/datalab/stackdriver/monitoring/__init__.py#L17

Is it possible there is some dependency issue?

**Comment by elgalu** [comment]
This solved the issue:

```
pip install google-cloud-monitoring==0.28.1
```

The change log states there ware changes regarding aligner and reducer after that version:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/monitoring/CHANGELOG.md#0281

**Comment by rileyjbauer** [comment]
Thanks for bringing this up! This should be fixed as of #705
