### ISSUE TITLE
datalab ml python3 compatibility

### ISSUE THREAD

**Issue by alienczf** [googledatalab/pydatalab#706]
Encountered a bit of python2to3 issues with the ml job library.

```
/usr/local/envs/py3env/lib/python3.5/site-packages/google/datalab/ml/_job.py in submit_training(job_request, job_id)
     87       job_args = job_request['args']
     88       args = []
---> 89       for k, v in job_args.iteritems():
     90         if isinstance(v, list):
     91           for item in v:
```

I don't mind contributing but I can't seem to get the tox tests working properly. If someone can give some pointers in terms of setting up will be nice but otherwise this is something that requires a bit of `six` magic to fix

**Comment by yebrahim** [comment]
Thanks for reporting this, we'd be happy to review a PR to fix it!

If you're having trouble setting up the tox environment locally, you can install the dependencies from the [tox file](https://github.com/googledatalab/pydatalab/blob/master/tox.ini#L31) for python2 in a virtualenv and run the tests, then send a pull request. Travis will take care of running the full suite of tests anyway.

**Comment by alienczf** [comment]
getting CA cert errors when running tox.. Any ideas how to set it up properly? I'm running on fedora (redhat)

```2018-09-08 12:03:35.156477: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 32.7013 seconds (attempt 6 out of 10), caused by: Unavailable: Error executing an HTTP request (error code 77, error message 'Problem with the SSL CA cert (path? access rights?)')
	Performing request. Detailed error: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
	 when reading gs://cloud-ml-data/img/flower_photos/daisy/15207766_fc2f1d692c_n.jpg
```

**Comment by yebrahim** [comment]
I think it's because the integration tests run against data in GCS.

You can just run the unit tests by doing `python tests/main.py --unittestonly`, no need to run the full suite of tests. Travis will take care of that for you.

**Comment by alienczf** [comment]
fyi i have a MR open for this fix ^

**Comment by yebrahim** [comment]
Merged. Thanks for the contribution @alienczf.
