### ISSUE TITLE
import error for the ML module while using in Jupyter

### ISSUE THREAD

**Issue by supriyagarg** [googledatalab/pydatalab#81]
Running pydatalab within Jupyter, gives an import error for the ML module. Within Datalab, it works fine.

```
ImportError: No module named ml
```

I guess the required libraries need to be included in setup.py?

**Comment by ojarjur** [comment]
Yes, here's the dependency: https://github.com/googledatalab/datalab/blob/master/containers/base/Dockerfile#L130

I'll see if I can figure out how to put that in the pydatalab setup.py

**Comment by chmeyers** [comment]
This is likely obsolete with the 1.0.0 version of pydatalab
